### ISSUE TITLE
Is it possible to choose the fonts of title page and contents?

### ISSUE THREAD

**Issue by proafxin** [Jinwen-XU/colorist#6]
I would like to use the normal font rather than sffamily for title page and contents. I am personally not a big fan of sffamily fonts. I was wondering if there was a way to keep them to default ones.

**Comment by Jinwen-XU** [comment]
If you are using XeLaTeX or LuaLaTeX, then it is possible to switch the sans serif font to the (almost) default via
```latex
\setsansfont{NewCMSans10}
  [
    Scale          = 1.05 ,
    Extension      = .otf,
    UprightFont    = *-Regular,
    BoldFont       = *-Bold,
    ItalicFont     = *-Oblique,
    BoldItalicFont = *-BoldOblique,
  ]
```
or
```latex
\setsansfont{lmsans10}
  [
    Scale          = 1.05 ,
    Extension      = .otf,
    UprightFont    = *-regular,
    BoldFont       = *-bold,
    ItalicFont     = *-oblique,
    BoldItalicFont = *-boldoblique,
  ]
```

For pdfLaTeX, the sans serif font is set by the package `newpxtext`, and I don't know an easy way to undo this.

-----

As an end note, the reason that I didn't use the default sans serif font is that it does not provide some combinations like `sc+bf`, which, if you enable both the options `title in boldface` and `title in scshape`, would look not quite satisfactory.

**Comment by proafxin** [comment]
Thank you. For pdflatex, I was able to circumvent it to some extent like this:

```latex
\documentclass{book}
\usepackage{colorist}
\TitlePage [ color = { main = forestgreen!75!black, back = forestgreen!10!yellow!30 } ]
	{
		, title     = \normalfont\textsc{Title}
		, subtitle  = 
		, author    = \normalfont{Masum Billal}
		, date      = {}
	}
```
